---
# TODO: Consider adding "upgrade=full" to also update everything.
- name: Ensure apt cache is updated.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure correct kernel headers are installed.
  shell: "apt-get -y install linux-headers-$(uname -r)"
  args:
    warn: no

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

# SSH configuration.
- name: Configure .ssh directory for the industrial user.
  file:
    path: /home/industrial/.ssh
    state: directory
    owner: industrial
    group: industrial
    mode: 0700

- name: Configure authorized SSH keys.
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/industrial/.ssh/authorized_keys
    owner: industrial
    group: industrial
    mode: 0600

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat: path=/home/industrial/.vbox_version
  register: virtualbox_check

- include: virtualbox.yml
  when: virtualbox_check.stat.exists

# VMware tools installation.
- name: Check if VMWare is running the guest VM.
  shell: "dmesg | grep VMware | wc -l"
  changed_when: false
  failed_when: false
  register: vmware_check

- include: vmware.yml
  when: vmware_check.stdout | int > 0

# Cleanup tasks.
- name: Remove unneeded packages.
  apt: "name={{ item }} state=absent"
  with_items:
    - ppp
    - pppconfig
    - pppoeconf
    - cpp
    - gcc
    - g++
    - libx11-data
    - xauth
    - libxmuu1
    - libxcb1
    - libx11-6
    - libxext6
    - linux-source

- name: Remove unneeded packages (by regex).
  shell: "apt-get -y remove '.*-dev$'"

- name: Clean up apt.
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
